name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: setup minikube
      uses: medyagh/setup-minikube@latest

    - name: Ensure Minikube is running
      run: |
        minikube status || minikube start

    - name: Set up kubeconfig
      run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/backend-deployment.yml --validate=false
        kubectl apply -f k8s/frontend-deployment.yml --validate=false
