name: CI/CD Pipeline new

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup KinD cluster
      uses: helm/kind-action@v1.5.0

    # - name: Ensure Minikube is running
    #   run: |
    #     minikube status || minikube start

    # - name: Set up kubectl
    #   run: |
    #     kubectl config use-context minikube

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/backend-deployment.yml --validate=false
        kubectl apply -f k8s/frontend-deployment.yml --validate=false
